### PR TITLE
Fixes the slowdowns and bugs caused by the prior improved compute practices, but requires a nested tensor package.

### LINKED ISSUE #73: DataLoader with num_workers > 0 increases memory consumption over time
Using the dev branch, I have noticed that when using DataLoader with num_workers greater than 0, the memory consumption increases over time during a single epoch. This problem has been documented here: 
https://docs.aws.amazon.com/codeguru/detector-library/python/pytorch-data-loader-with-multiple-workers/
https://github.com/pytorch/pytorch/issues/13246#issuecomment-905703662

### PR DESCRIPTION
**Pull request by mmcdermott**
This should fix #73 as well

### CODE REVIEW

**Comment by juancq** [comment]
@mmcdermott what polars and numpy version were used for this branch? 

I tested this building the dataset works fine. 

When running pretrain, I initially got a runtime error here: 
https://github.com/mmcdermott/EventStreamGPT/blob/29c3b9f53f8b1d1e16188f81a18face2d1c4adce/EventStream/data/pytorch_dataset.py#L253-L255

The error being: 
`ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (55877,) + inhomogeneous part.`

When I change the numpy array dtype to object, it just hangs (it runs for an incredibly long time, and I haven't been patient enough to wait it out). I don't know whether safetensors or the nested_ragged_tensors are to blame (I assume the latter). This occurs when trying to run pretrain, sampling about 90,000 subjects from a full dataset of about 600,000.

**Comment by mmcdermott** [comment]
@juancq , definitely don't feel obliged to wait it out when setting it to an object; that will be very slow and defeats the purpose of this change. One question, though; in your data do you have reason to believe that your subjects will have varying numbers of observations of _static_ measurements per row? I believe that what is going on here is that something that is treated as a dense tensor is in reality a ragged one.

**Comment by juancq** [comment]
> @juancq , definitely don't feel obliged to wait it out when setting it to an object; that will be very slow and defeats the purpose of this change. One question, though; in your data do you have reason to believe that your subjects will have varying numbers of observations of _static_ measurements per row? I believe that what is going on here is that something that is treated as a dense tensor is in reality a ragged one.

I don't follow, what would be an example? 

This branch also has parts that break with certain polars versions. This makes it hard to test because I don't know which exact polar version to use.

**Comment by juancq** [comment]
@mmcdermott I have sorted out polars issues and have gotten further testing this. 

My pretraining now hangs here: 
https://github.com/mmcdermott/EventStreamGPT/blob/fa33387247f43e760d11c117c3eec5a983778f2d/EventStream/data/pytorch_dataset.py#L161

When I kill the script, the stack trace is something along the following lines (in ragged tensors):

__get__item__ https://github.com/mmcdermott/nested_ragged_tensors/blob/b3a01a661e73e9c55541430dbb985c51d054fa4d/src/nested_ragged_tensors/ragged_numpy.py#L398

vstack https://github.com/mmcdermott/nested_ragged_tensors/blob/b3a01a661e73e9c55541430dbb985c51d054fa4d/src/nested_ragged_tensors/ragged_numpy.py#L655

concatenate https://github.com/mmcdermott/nested_ragged_tensors/blob/b3a01a661e73e9c55541430dbb985c51d054fa4d/src/nested_ragged_tensors/ragged_numpy.py#L754

If this is too cryptic, let me know and I'll rephrase or can post an issue on nested_ragged_tensors repo.

**Comment by mmcdermott** [comment]
Thank you @juancq -- I've been travelling quite a bit and been otherwise occupied for the last month and a half, but I'm trying to push a new major version of ESGPT that addresses these issues and the other memory issues. I assume your last comment still reflects the state of things with this change for you?

**Comment by mmcdermott** [comment]
@coderabbitai review

**Comment by juancq** [comment]
> Thank you @juancq -- I've been travelling quite a bit and been otherwise occupied for the last month and a half, but I'm trying to push a new major version of ESGPT that addresses these issues and the other memory issues. I assume your last comment still reflects the state of things with this change for you?

Yes, the state of things on my end are the same as of the time I wrote the last comment.

**Comment by mmcdermott** [comment]
This is blocked by #104

**Comment by mmcdermott** [comment]
@juancq I know this update is long overdue, but the recent pushes use the nested ragged tensor code in a new way that should dramatically reduce the CPU memory burden during model training. You'll need to re-build the base dataset object first to produce the right cached files (though I may write a conversion script to ease that cost, if that would be helpful) but once that is done this should, with minimal to no impact on throughput, set things up to only pull the patient data from disk as needed rather than loading it all in memory at all. Note this requires updating to the latest version of nested_ragged_tensors as well. If you try it and find it useful or find issues with it, I'd be very appreciative and curious of your findings!

**Comment by juancq** [comment]
@mmcdermott thanks for all the hard work. I tested this branch on my dataset. The previous bugs are gone. I am now seeing about a 7% runtime improvement per epoch and about 30% lower memory usage.

**Comment by mmcdermott** [comment]
Fantastic! Thanks so much @juancq . I'll do some final testing just to make sure there are no issues and plan to merge this branch in soon. Glad this has resolved your issues and induced other improvements besides.

**Pull request merged**
